apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: linkerd2
spec:
  title: Linkerd2
  icon: https://linkerd.io/images/logo-only-200h.png
  statusInformers:
    - deployment/linkerd-destination
    - deployment/linkerd-identity
    - deployment/linkerd-proxy-injector
  ports: []
